<?php

// Single-character tokens
define('TOKEN_LEFT_PARENTHESIS', 'TOKEN_LEFT_PARENTHESIS');
define('TOKEN_RIGHT_PARENTHESIS', 'TOKEN_RIGHT_PARENTHESIS');
define('TOKEN_LEFT_BRACE', 'TOKEN_LEFT_BRACE');
define('TOKEN_RIGHT_BRACE', 'TOKEN_RIGHT_BRACE');
define('TOKEN_COMMA', 'TOKEN_COMMA');
define('TOKEN_DOT', 'TOKEN_DOT');
define('TOKEN_MINUS', 'TOKEN_MINUS');
define('TOKEN_PLUS', 'TOKEN_PLUS');
define('TOKEN_SEMICOLON', 'TOKEN_SEMICOLON');
define('TOKEN_SLASH', 'TOKEN_SLASH');
define('TOKEN_STAR', 'TOKEN_STAR');

// One or two character tokens
define('TOKEN_BANG', 'TOKEN_BANG');
define('TOKEN_BANG_EQUAL', 'TOKEN_BANG_EQUAL');
define('TOKEN_EQUAL', 'TOKEN_EQUAL');
define('TOKEN_EQUAL_EQUAL', 'TOKEN_EQUAL_EQUAL');
define('TOKEN_GREATER', 'TOKEN_GREATER');
define('TOKEN_GREATER_EQUAL', 'TOKEN_GREATER_EQUAL');
define('TOKEN_LESS', 'TOKEN_LESS');
define('TOKEN_LESS_EQUAL', 'TOKEN_LESS_EQUAL');

// Literals
define('TOKEN_IDENTIFIER', 'TOKEN_IDENTIFIER');
define('TOKEN_STRING', 'TOKEN_STRING');
define('TOKEN_NUMBER', 'TOKEN_NUMBER');

// Keywords
define('TOKEN_AND', 'TOKEN_AND');
define('TOKEN_CLASS', 'TOKEN_CLASS');
define('TOKEN_ELSE', 'TOKEN_ELSE');
define('TOKEN_FALSE', 'TOKEN_FALSE');
define('TOKEN_FUNCTION', 'TOKEN_FUNCTION');
define('TOKEN_FOR', 'TOKEN_FOR');
define('TOKEN_IF', 'TOKEN_IF');
define('TOKEN_LET', 'TOKEN_LET');
define('TOKEN_NULL', 'TOKEN_NULL');
define('TOKEN_OR', 'TOKEN_OR');
define('TOKEN_PRINT', 'TOKEN_PRINT');
define('TOKEN_RETURN', 'TOKEN_RETURN');
define('TOKEN_PARENT', 'TOKEN_PARENT');
define('TOKEN_THIS', 'TOKEN_THIS');
define('TOKEN_TRUE', 'TOKEN_TRUE');
define('TOKEN_WHILE', 'TOKEN_WHILE');

// Misc
define('TOKEN_EOF', 'TOKEN_EOF');