#! /usr/bin/env php

<?php

require 'vendor/autoload.php';

use Axiom\Ghost\Ghost;
use Axiom\Ghost\Console\ASTCommand;
use Axiom\Ghost\Console\REPLCommand;
use Symfony\Component\Console\Application;

$ghost       = new Ghost;
$ASTCommand  = new ASTCommand();
$REPLCommand = new REPLCommand($ghost);
$application = new Application('Ghost Interactive Shell');

$application->add($ASTCommand);
$application->add($REPLCommand);

$application->setDefaultCommand($REPLCommand->getName());

$application->run();